
name: Loveca Jp Update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

jobs:
  automate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install httpx
      run: pip install httpx

    - name: Update loveca
      run: python database.py
      
    - name: Detect Changes
      id: check-changes
      run: |
        git status --porcelain
        if [ -n "$(git status --porcelain)" ]; then
            echo "changes_detected=true" >> $GITHUB_OUTPUT
        else
            echo "changes_detected=false" >> $GITHUB_OUTPUT
        fi

    - name: Commit
      if: steps.check-changes.outputs.changes_detected == 'true'
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Auto-commit: $(date +'%Y-%m-%d %H:%M:%S')"
        git pull --rebase

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.COMMIT_TOKEN }}